app:
  NODE_ENV: $ENV
  url: $URL
  frontend: $FRONTEND

http:
  host: 0.0.0.0

database:
  host: $DATABASE_HOST
  port: 5432
  username: $DATABASE_USERNAME
  password: $DATABASE_PASSWORD
  database: $DATABASE_NAME

auth:
  google:
    clientId: $AUTH_GOOGLE_CLIENT_ID
    secret: $AUTH_GOOGLE_CLIENT_SECRET
  microsoft:
